panel/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
	url(r'^$', dashboard, name='dashboard'),
	# url(r'^video-posts/list/$', video_posts, name='video-posts'),
	# url(r'^customers/list/$', customer_list, name='customer-list'),
	url(r'^customers/list/(?P<type>[\w-]+)/$', customer_list_type, name='customer-list-type'),
	url(r'^customers/list/m/ajax/$', customer_list_ajax, name='customer-ajax-list'),
	url(r'^customers/create/$', add_customer, name='customer-create'),
	url(r'^customers/edit/(?P<id>[0-9]+)/$', edit_customer, name='customer-edit'),

	url(r'^packages/annuitet/(?P<id>[0-9]+)/$', package_annuitet, name='package-annuitet'),
	url(r'^packages-an/annuitet-general/$', general_annuitet, name='general-annuitet'),
	url(r'^packages-an/upload_base64/$', upload_base64, name='upload_base64'),


	url(r'^statistic/(?P<type>[\w-]+)/$', statistic_type, name='statistic-type'),




	url(r'^packages/list/$', package_list, name='package-list'),
	url(r'^packages/list/(?P<type>[\w-]+)/$', package_list_type, name='package-list-type'),
	url(r'^packages/list/infinity/(?P<type>[\w-]+)/$', package_list_type_infinity, name='package-list-type-infinity'),
	url(r'^packages/package-daily-note-write/(?P<id>[0-9]+)/$', package_daily_note_ajax, name='package-daily-note'),
	url(r'^packages/package-daily-note-list/(?P<id>[0-9]+)/$', package_daily_note_list, name='package-daily-list'),
	url(r'^product-type/get-ajax/$', product_type_ajax, name='product-type-ajax'),
	url(r'^packages/closed-reason/(?P<id>[0-9]+)/$', package_closed_reason, name='package-closed-reason'),
	url(r'^packages/waiting/list/(?P<type>[\w-]+)/$', package_waiting_list, name='package-waiting-list'),
	url(r'^packages/waiting/edit/(?P<id>[0-9]+)/$', package_waiting_edit, name='package-waiting-edit'),
	url(r'^packages/waiting/list/(?P<p_id>[0-9]+)/(?P<type>[\w-]+)/$', package_waiting_list_package, name='package-waiting-list-package'),

	url(r'^packages/create/$', package_create, name='package-create'),
	url(r'^packages/edit/(?P<id>[0-9]+)/$', package_edit, name='package-edit'),
	url(r'^package-atachment-upload/(?P<id>[0-9]+)/ajax/$', package_atachment_upload, name='package-atachment-upload'),



	url(r'^packages/payments-edit/(?P<id>[0-9]+)/$', package_payment_edit, name='package-payments-edit'),
	url(r'^packages/payments-refresh/(?P<id>[0-9]+)/$', package_payment_refresh, name='package-payments-refresh'),
	url(r'^packages/payments-remove/(?P<id>[0-9]+)/$', package_payment_remove, name='package-payments-remove'),
	url(r'^packages/payments-new-generate/(?P<id>[0-9]+)/$', package_payment_new_generate, name='package-payments-new-generate'),
	url(r'^packages/payment-new-check/(?P<id>[0-9]+)/$', package_payment_new_check, name='package-payment-new-check'),
	url(r'^packages/payment-new-add/(?P<id>[0-9]+)/$', package_payment_new_add, name='package-payment-new-add'),
	url(r'^packages/payment-ajax/(?P<id>[0-9]+)/$', package_payment_add, name='package-add-paymanet'),

	url(r'^packages/ordered/list/$', package_ordered_list, name='package-ordered-list'),
	url(r'^packages/next/(?P<o_slug>[\w-]+)/(?P<id>[0-9]+)/$', package_next, name='package-next'),
	url(r'^packages/ordered/edit/(?P<id>[0-9]+)/$', package_ordered_edit, name='package-ordered-edit'),

    url(r'^salaries/list/$', salary_list, name='salary-list'),
	url(r'^employees/list/$', employee_list, name='employee-list'),
	url(r'^employees/create/$', employee_create, name='employee-create'),
	url(r'^employees/edit/(?P<id>[0-9]+)/$', employee_edit, name='employee-edit'),

	url(r'^employees-permit/list/$', employee_permit_list, name='employee-permit-list'),
	url(r'^employees-permit/create/$', employee_permit_create, name='employee-permit-create'),
	url(r'^employees-permit/edit/(?P<id>[0-9]+)/$', employee_permit_edit, name='employee-permit-edit'),

	url(r'^reports/logs/list/$', log_list, name='log-list'),
	url(r'^reports/logs/outcome/ajax/$', logo_outcome_data_ajax, name='logo-outcome-ajax-data-list'),
	url(r'^reports/logs/detail/(?P<id>[0-9]+)/$', log_detail, name='log-detail'),
	url(r'^reports/(?P<o_slug>[\w-]+)/list/$', income_outcome_list, name='income-outcome-list'),
	url(r'^reports/list/kassa/$', income_outcome_case, name='income-outcome-case'),
	url(r'^reports/list/kassa/$', income_outcome_case, name='income-outcome-case'),
	url(r'^reports/(?P<o_slug>[\w-]+)/create/$', income_outcome_create, name='income-outcome-create'),
	url(r'^reports/(?P<o_slug>[\w-]+)/edit/(?P<id>[0-9]+)/$', income_outcome_edit, name='income-outcome-edit'),


	url(r'^currency/list/$', currency_list, name='currency-list'),
	url(r'^currency/create/$', currency_create, name='currency-create'),
	url(r'^currency/edit/(?P<id>[0-9]+)/$', currency_edit, name='currency-edit'),

	url(r'^customer-notes/list/(?P<c_id>[0-9]+)/$', customer_notes_list, name='customer-notes-list'),
	url(r'^customer-notes/create/(?P<c_id>[0-9]+)/$', customer_notes_create, name='customer-notes-create'),
	url(r'^customer-notes/edit/(?P<c_id>[0-9]+)/(?P<id>[0-9]+)/$', customer_notes_edit, name='customer-notes-edit'),

	url(r'^departments/list/', department_list, name='department-list'),
	url(r'^departments/create/', department_create, name='department-create'),
	url(r'^departments/edit/(?P<id>[0-9]+)/', department_edit, name='department-edit'),

	url(r'^package-types/list/', package_type_list, name='package_type-list'),
	url(r'^package-types/create/', package_type_create, name='package_type-create'),
	url(r'^package-types/edit/(?P<id>[0-9]+)/', package_type_edit, name='package_type-edit'),
	url(r'^package-types/remove/(?P<id>[0-9]+)/', package_type_remove, name='package_type-remove'),

	url(r'^product/list/', product_list, name='product-list'),
	url(r'^product/create/', product_create, name='product-create'),
	url(r'^product/edit/(?P<id>[0-9]+)/', product_edit, name='product-edit'),
	url(r'^product/remove/(?P<id>[0-9]+)/', product_remove, name='product-remove'),

	url(r'^product-type/generate/', product_generate, name='product-type-generate-ajax'),
	url(r'^product-type/list/(?P<p_id>[0-9]+)/', product_type_list, name='product-type-list'),
	url(r'^product-type/create/(?P<p_id>[0-9]+)/', product_type_create, name='product-type-create'),
	url(r'^product-type/edit/(?P<p_id>[0-9]+)/(?P<id>[0-9]+)/', product_type_edit, name='product-type-edit'),
	url(r'^product-type/remove/(?P<p_id>[0-9]+)/(?P<id>[0-9]+)/', product_type_remove, name='product-type-remove'),

	url(r'^package-product/remove/(?P<id>[0-9]+)/', package_product_remove, name='package-product-image-remove'),


 ]

panel/models.py
import datetime
import decimal
import uuid

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.db import models
from django.db.models import signals

from django.utils.translation import ugettext_lazy as _

# Create your models here.
from general.functions import path_and_rename

from django.utils import timezone

from panel.functions import monthdelta, months_between, change_data
from panel.tasks import package_utility_date

PERMIT_CHOİCE = (
    ("","Səbəb"),
    ("permit","İcaze"),
    ("late","Gecikmə"),
    ("penalty","Cərimə"),
)

class EmployeeSalary(models.Model):
    employee = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="+")
    month = models.IntegerField()
    year = models.IntegerField()
    work_minute = models.IntegerField(default=0)
    salary_amount = models.DecimalField("Miqdar",max_digits=19,decimal_places=2,default=0)
    result_amount = models.DecimalField("Miqdar",max_digits=19,decimal_places=2,default=0)
    penalty = models.DecimalField("Cərimə",max_digits=19,decimal_places=2,default=0)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return "{} {}".format(self.employee.first_name,self.employee.last_name)
    class Meta:
        unique_together = ('employee', 'month', 'year',)


class EmployeePermit(models.Model):
    employee = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="+")
    reason = models.CharField(max_length=100,choices=PERMIT_CHOİCE)
    description = models.TextField(max_length=255)
    day = models.IntegerField()
    time  = models.TimeField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return "{} {}".format(self.employee.first_name,self.employee.last_name)
    def get_reason(self):
        ret_val = ''
        for item in PERMIT_CHOİCE:
            if item[0] == self.reason:
                ret_val = item[1]
        return ret_val




GenderChoice = (
    ('','Cins'),
    ('man','Kişi'),
    ('woman','Qadın'),
)

class Customer(models.Model):
    full_name = models.CharField(max_length=255)
    # father_name = models.CharField(_('Ata adi'), max_length=255, blank=True)
    serial_number = models.CharField(max_length=255)
    fin = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    gender = models.CharField(choices=GenderChoice,max_length=255,default='man')
    contact_number = models.CharField(max_length=255)
    birthdate = models.DateField(verbose_name="ad günü",blank=True,null=True)
    id_number = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    is_active = models.BooleanField(_('active'), default=True,)
    profile_picture = models.ImageField(upload_to=path_and_rename, null=True, blank=True)
    passport_picture1 = models.ImageField(upload_to=path_and_rename, null=True, blank=True)
    passport_picture2 = models.ImageField(upload_to=path_and_rename, null=True, blank=True)
    department = models.ForeignKey('Department',blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def get_phones(self):
        return CustomerPhoneNumber.objects.filter(customer=self)
    def get_packages_info(self):
        packs = Package.objects.filter(customer=self)
        return [packs.filter(status='active').count(),packs.exclude(status='active').count(),packs.all().count()]
    def __str__(self):
        return self.full_name
    def get_package_status(self):
        pack_list = Package.objects.filter(customer=self)
        active_packs = pack_list.filter(status__in=['active','waiting']).order_by('-first_date')
        not_active_packs = pack_list.exclude(status__in=['active','waiting']).order_by('-end_date')
        saled_packs = pack_list.filter(status='saled').order_by('-end_date')
        return_val = ['-','Paketi olmayıb','no-package','no-saled']
        if active_packs.count()>0:
            c_date = active_packs.first().first_date
            return_val = ["{}-{}-{} {}:{}".format(c_date.day,c_date.month,c_date.year,c_date.hour,c_date.minute,),'Aktiv','active']
        elif not_active_packs.count() > 0:
            if active_packs.first():
                c_date = active_packs.first().end_date
                return_val = ["{}-{}-{} {}:{}".format(c_date.day,c_date.month,c_date.year,c_date.hour,c_date.minute,),'Deaktiv','deactive']
            # else:
            #     c_date = active_packs.first().end_date
        if saled_packs.count() > 0:
            return_val.append('saled')
        else:
            return_val.append('no-saled')
        return return_val



class CustomerPhoneNumber(models.Model):
    customer = models.ForeignKey('Customer', blank=True, null=True)
    number = models.CharField(max_length=255)

    def __str__(self):
        return self.number


AnnuitetStatusChoice = (
    ('','Hamısı'),
    (1,'Annuitet'),
    (0,'Adi'),
)

PackageStatusChoice = (
    ('','Status'),
    ('active','Aktiv'),
    ('waiting','Yoxlamada'),
    ('paided','Bağlandı'),
    ('ordered','--- Sifarişə verildi'),
    ('closed','--- Təhvil verildi'),
    ('saled','Satıldı'),
)
ShowPhotoChoice = (
    ('hide','Gizlə'),
    ('show','Göstər'),
)
PackageStatusFormChoice = (
    ('','Status'),
    ('active','Aktiv'),
    ('waiting','Yoxlamada'),
    ('paided-all','Bağlandı'),
    ('paided', '--- Ödəmə tamamlandı'),
    ('ordered','--- Sifarişə verildi'),
    ('closed','--- Təhvil verildi'),
    ('saled','Satıldı'),
)

class PackageProduct(models.Model):
    package = models.ForeignKey('Package',blank=True,null=True)
    product_type = models.ForeignKey('ProductType',blank=True,null=True)
    product_amount = models.DecimalField("Miqdar",max_digits=10,decimal_places=2,default=0)
    date = models.DateTimeField(auto_now_add=True)




class PackageProductImage(models.Model):
    package = models.ForeignKey('Package',blank=True,null=True)
    image = models.ImageField(upload_to=path_and_rename, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)




class Package(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="+",blank=True,null=True)
    customer = models.ForeignKey('Customer',blank=True,null=True)
    pledge_number = models.CharField(max_length=255,verbose_name="Girov nomresi")
    currency  = models.ForeignKey("Currency")

    first_date = models.DateTimeField(verbose_name="ilk tarix",blank=True,null=True)
    end_date = models.DateField(verbose_name="son tarix",blank=True,null=True)
    notes = models.TextField(blank=True,null=True)
    closed_reason = models.TextField(default='',blank=True,null=True)

    amount = models.DecimalField("Miqdar",max_digits=19,decimal_places=2)
    percent = models.DecimalField(max_digits=10,decimal_places=2)
    debt_amount = models.DecimalField("Qalan miqdar",max_digits=19,decimal_places=2,default=0.0)
    total_debt_extra = models.DecimalField("Qalan Faiz",max_digits=19,decimal_places=2,default=0.0)
    # amount_dollar = models.DecimalField("Miqdar",max_digits=19,decimal_places=2)
    # status = models.ForeignKey('PackageStatus', blank=True,null=True)
    status = models.CharField(max_length=100,default="",choices=PackageStatusChoice)

    packet_type = models.ForeignKey('PackageType')
    department = models.ForeignKey('Department')
    annuitet = models.BooleanField(default=False)

    product = models.ForeignKey('Product',blank=True,null=True)
    product_type = models.ForeignKey('ProductType',blank=True,null=True)
    product_amount = models.DecimalField("Miqdar",max_digits=10,decimal_places=2,default=0)
    last_payment_date = models.DateTimeField(blank=True,null=True)


    pay_date = models.DateField(verbose_name="odeme tarixi",blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    delay_day = models.IntegerField("Gecikmə",default=0)
    def __str__(self):
        return "{}-{}".format(self.id,self.customer.full_name)
    def get_last_order(self):
        return PackageOrder.objects.filter(package=self).order_by('-date').first()
    def get_last_daily_note(self):
        return PackageDailyNote.objects.filter(package=self).exclude(date__year=datetime.datetime.now().year,date__month=datetime.datetime.now().month,date__day=datetime.datetime.now().day,).order_by('-date').last()
    def get_last_payment(self):
        obj = PackagePaymentDates.objects.filter(package=self).order_by('-date').first()
        return obj.date + relativedelta(months=+1) if obj else self.first_date  + relativedelta(months=+1)
    def get_last_payment_real(self):
        obj = PackagePaymentDates.objects.filter(package=self).order_by('-date')
        mounth_count = 0
        for item in obj:
            mounth_count += item.month_count
        return self.first_date  + relativedelta(months=+(mounth_count+1))
    def get_pay_amount(self):
        return self.amount - self.debt_amount
    def get_monthly_percent(self):
        return self.debt_amount * self.percent / 100

def package_item_save(sender, instance, created, *args, **kwargs):
    # pass
    print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
    if created:
        package_utility_date([instance.id])

#
signals.post_save.connect(package_item_save, sender=Package)


class PackageDailyNote(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="+",blank=True,null=True)
    package = models.ForeignKey('Package',blank=True,null=True)
    content = models.CharField(max_length=255,blank=True,null=True,default='')
    date = models.DateTimeField(auto_now_add=True)


class Product(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    removed = models.BooleanField(default=False)


class ProductType(models.Model):
    product = models.ForeignKey('Product',blank=True,null=True)
    title = models.CharField(max_length=255)
    removed = models.BooleanField(default=False)

templates/panel/employees/permit/add-edit.html
{% extends 'panel-base.html' %}
{% load static %}{% load i18n %}
{% block title_block %}

{% endblock %}
{% block css_block %}

{% endblock %}
{% block content_block %}
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-sm-flex flex-nowrap align-items-center">
                        <div class="page-title mb-2 mb-sm-0">
                            <h1>
                                {% trans "İcazə" %} {% if data_obj %} - {{ data_obj.title }}{% else %} {% trans 'Əlavə et' %} {% endif %}
                            </h1>
                        </div>
                        <div class="ml-auto d-flex align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:dashboard' %}"><i class="ti ti-home"></i></a>
                                    </li>
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:employee-permit-list' %}">{% trans 'İcazələr' %}</a>
                                    </li>
                                    <li class="breadcrumb-item active text-primary">
                                        {% trans "İcazə" %} {% if data_obj %} - {{ data_obj.title }}{% else %} {% trans 'Əlavə et' %} {% endif %}
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                    <!-- end page title -->
                </div>
            </div>
            <!-- end row -->
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-statistics">
                        <div class="card-header">
                            <div class="card-heading">
                                <h4 class="card-title">
                                    {% trans "İcazə" %} {% if data_obj %} - {{ data_obj.full_name }}{% else %} {% trans 'Əlavə et' %} {% endif %}
                                </h4>
                            </div>
                        </div>
                        <form class="card-body" method="post" action="">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">{% trans 'İşçi' %}</span>
                                </div>
                                {{ form.employee }}
                            </div>
                            {% if form.employee.errors %}
                                <div class="alert alert-danger mb-3" role="alert">
                                    {{ form.employee.errors }}
                                </div>
                            {% endif %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">{% trans 'Səbəb' %}</span>
                                </div>
                                {{ form.reason }}
                            </div>
                            {% if form.reason.errors %}
                                <div class="alert alert-danger mb-3" role="alert">
                                    {{ form.reason.errors }}
                                </div>
                            {% endif %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">{% trans 'Gün' %}</span>
                                </div>
                                {{ form.day }}
                            </div>
                            {% if form.day.errors %}
                                <div class="alert alert-danger mb-3" role="alert">
                                    {{ form.day.errors }}
                                </div>
                            {% endif %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">{% trans 'Saat' %}</span>
                                </div>
                                {{ form.time }}
                            </div>
                            {% if form.time.errors %}
                                <div class="alert alert-danger mb-3" role="alert">
                                    {{ form.time.errors }}
                                </div>
                            {% endif %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">{% trans 'Qeyd' %}</span>
                                </div>
                                {{ form.description }}
                            </div>
                            {% if form.description.errors %}
                                <div class="alert alert-danger mb-3" role="alert">
                                    {{ form.description.errors }}
                                </div>
                            {% endif %}
                            <button type="submit" class="btn btn-block btn-success">
                                {% if data_obj %} - {% trans 'Dəyiş' %} {% else %} {% trans 'Əlavə et' %} {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container-fluid -->
    </div>
    <!-- end app-main -->
{% endblock %}
{% block js_block %}
    <script>
        activeMenu('personal-control');
        {#activeMenu('personal-control');#}
    </script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>

<script>
$('#id_time').inputmask("hh:mm:ss", {
        placeholder: "HH:MM:SS",
        insertMode: false,
        showMaskOnHover: false,
        hourFormat: 12
      }
   );

    $('.js-basic-single').select2();
    {#$('.js-basic-single').select2();#}
</script>
<script>
    {% if success_message %}
        swal({
            type: 'success',
            title: '{% trans 'Success' %}',
            text: '{{ success_message }}'
        });
    {% endif %}
</script>

{% endblock %}

templates/panel/employees/permit/list.html
{% extends 'panel-base.html' %}
{% load static %}{% load i18n %}
{% block title_block %}
{% trans 'İcazələr' %}
{% endblock %}
{% block css_block %}
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <style>
    .dt-buttons .dt-button{
        padding:.5rem 1.6rem!important;
        border-radius: 5px;
        border:none;
        cursor: pointer;
        background: #8d8d8d;
        color:#fff!important
    }
    .dt-buttons .dt-button:hover{
        border:none;
        background: #3a3d44;
        color:#fff!important
    }

    </style>
{% endblock %}
{% block content_block %}
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-sm-flex flex-nowrap align-items-center">
                        <div class="page-title mb-2 mb-sm-0">
                            <h1>
                                {% trans "İcazələr" %}
                            </h1>
                        </div>
                        <div class="ml-auto d-flex align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:dashboard' %}"><i class="ti ti-home"></i></a>
                                    </li>
                                    <li class="breadcrumb-item active text-primary">
                                        {% trans "İcazələr" %}
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                    <!-- end page title -->
                </div>
            </div>
            <!-- end row -->
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-statistics">
                        <div class="card-header">
                            <div class="card-heading">
                                <h4 class="card-title">
                                    {% trans "İcazələr" %}
                                </h4>
                            <hr/>
                            <a class="btn btn-success" href="{% url 'panel:employee-permit-create' %}"> {% trans 'Əlavə et' %}</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>N</th>
                                        <th>{% trans 'Səbəb' %}</th>
                                        <th>{% trans 'İşçi' %}</th>
                                        <th>{% trans 'Saat' %}</th>
                                        <th>{% trans 'Gün' %}</th>
                                        <th>{% trans 'qeyd' %}</th>
                                        <th>{% trans 'Tarix' %}</th>
                                        <th>/</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for data_item in data_list %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ data_item.get_reason }}</td>
                                            <td><a target="_blank" href="{% url 'panel:employee-edit' data_item.employee_id %}">{{ data_item.employee_id }} - {{ data_item.employee.first_name }}&nbsp;{{ data_item.employee.last_name }}</a> </td>
                                            <td>{{ data_item.time }}</td>
                                            <td>{{ data_item.day }}</td>
                                            <td>{{ data_item.description }}</td>
                                            <td>{{ data_item.date }}</td>
                                            <td>
                                                <a href="{% url 'panel:employee-permit-edit' data_item.id %}" class="btn btn-icon btn-square btn-warning">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>N</th>
                                        <th>{% trans 'Səbəb' %}</th>
                                        <th>{% trans 'İşçi' %}</th>
                                        <th>{% trans 'Saat' %}</th>
                                        <th>{% trans 'Gün' %}</th>
                                        <th>{% trans 'Qeyd' %}</th>
                                        <th>{% trans 'Tarix' %}</th>
                                        <th>/</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container-fluid -->
    </div>
    <!-- end app-main -->
{% endblock %}
{% block js_block %}
    <script>
        activeMenu('personal-control');
        {#activeMenu('advanced-datas-2');#}
    </script>





<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.colVis.min.js "></script>
    <script>
    $(document).ready(function() {
    var table = $('#example').DataTable( {
        lengthChange: true,
        buttons: [ 'copy', 'excel', 'pdf' ]
    } );

    table.buttons().container()
        .appendTo( '#example_wrapper .col-md-6:eq(0)' );
} );
    </script>
{% endblock %}